# Generated by Django 4.1.5 on 2023-02-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
