# Generated by Django 4.1.5 on 2023-03-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_timerecord_total_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerecord',
            old_name='check_in_time',
            new_name='time_in',
        ),
        migrations.RenameField(
            model_name='timerecord',
            old_name='check_out_time',
            new_name='time_out',
        ),
    ]
