# Generated by Django 4.1.5 on 2023-03-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_coadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_coadmin',
        ),
    ]
