# Generated by Django 4.1.5 on 2023-03-09 10:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
