# Generated by Django 4.1.5 on 2023-03-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_mymodel_slug_alter_mymodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
